### ISSUE TITLE
100% CPU usage

### ISSUE THREAD

**Issue by greenfoo** [djt3/tuitube#1]
It looks like the main thread is constantly running, using 100% of CPU time.

It would be nice if instead of polling, the main thread blocked until a screen update is needed.

**Comment by djt3** [comment]
The main thread is blocked. I have tested on both st and konsole, what terminal are you using?

**Comment by djt3** [comment]
ah, didn't notice there was a cpu usage problem. it was due to how often the terminal dimensions were being queried. fixed with the latest commit.
