### ISSUE TITLE
missing invidious/instances.h but not listed in readme as external dependancy

### ISSUE THREAD

**Issue by ghost** [djt3/tuitube#11]
$ make
[ 33%] Building CXX object CMakeFiles/tuitube.dir/src/main.cpp.o
In file included from /home/e/git/tuitube/src/tui/tui.h:19,
                 from /home/e/git/tuitube/src/main.cpp:1:
/home/e/git/tuitube/src/tui/tabs/settings.h:7:10: fatal error: ../../invidious/instances.h: No such file or directory
    7 | #include "../../invidious/instances.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/tuitube.dir/build.make:83: CMakeFiles/tuitube.dir/src/main.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:96: CMakeFiles/tuitube.dir/all] Error 2
make: *** [Makefile:150: all] Error 2

**Comment by djt3** [comment]
thanks for letting me know
