### ISSUE TITLE
Search Crashes

### ISSUE THREAD

**Issue by dualhammers** [djt3/tuitube#13]
Using FISH on Manjaro to launch the program.

![Screen Capture_xfce4-terminal_20200925125853](https://user-images.githubusercontent.com/7495830/94305728-e728a300-ff2e-11ea-98f5-a6b0951b4fdd.gif)

**Comment by djt3** [comment]
Looks like its inserting a line or something when you change tab, which is strange. 100% my fault though, ill add something to filter the characters entered in the search box.

**Comment by djt3** [comment]
Fixed in latest commit
