### ISSUE TITLE
Errors with Invidious & Sub List

### ISSUE THREAD

**Issue by Xeno-Hypster** [djt3/tuitube#15]
Hey,

Having issues with the two invidious instances available. Not sure if this is a tuitube or invidious issue, but the snopyta instance doesn't show subbed videos in the sub tab (no videos found) nor allows me to view channels, meanwhile the inidiou.site instance just perpetually loads.

Works a dream otherwise when I'm searching for particular vids with the snopyta instance!

**Comment by djt3** [comment]
invidious has been going down hill, ill move to scraping youtube at some point
