### ISSUE TITLE
tuitube search: not finding last recent uploads

### ISSUE THREAD

**Issue by sdsddsd1** [djt3/tuitube#2]
First of all good job with this nice programm!
Mainly I can find the right channels, but I encounterd an issue while searching for `decino` .
In tuitube I find the right channel but only the "top  clicked videos" and also when I want to add the 
supscription the most recent uploads are missing.
On invidous itself it´s no problem to find the channel.
Greetings.

**Comment by djt3** [comment]
Hi, thanks for the kind words about the program :)

I dont seem to have a problem with that specific channel. Have you changed the invidious instance and can you please provide screenshots of the issue. Also make sure you are on the latest version.

![Screenshot_20200506_183121](https://user-images.githubusercontent.com/60714836/81209052-80c2d880-8fbf-11ea-8d35-42c5fbcd933f.png)

Thanks.

**Comment by sdsddsd1** [comment]
Iam on KISS and have just rebuild 3 hours ago. 
Here is a [screenshot](https://ibb.co/0GvjMDF).  
I have not changed the invidious instance, I will look into this.

**Comment by djt3** [comment]
okay, i have no idea why that is happening. can you tell me what terminal you use and please provide the output of `cat /etc/locale.conf`. ill get kiss up and investigate further.

**Comment by sdsddsd1** [comment]
After your last commits the output looks like [this](https://ibb.co/nLxx0hT). While on this view its flickering hard.  
There is no `/etc/locale.conf` on my system.  
I am running alacritty in a wayland session but this should not matter? I hope this helps.
Ps: I have tested other instances but your provided works best so far.
Edit: I have tested in another terminal but same behaviour.

**Comment by djt3** [comment]
i am having the same problem on a chroot of kiss, ill do some more work and get back to you

**Comment by djt3** [comment]
okay so its something to do with the percentage % symbol being in the title. give me a bit i think i know whats happening.
edit: ive managed to fix it, thanks for reporting the issue :) I am sorting out some other things and then ill make a new commit and bump the version.

**Comment by djt3** [comment]
fixed in the latest commit. thanks again for reporting the issue.
