### ISSUE TITLE
Feature request: Upload date and play duration

### ISSUE THREAD

**Issue by sdsddsd1** [djt3/tuitube#3]
As the title says, are you planing to add `date of upload` and `play duration`?
Maybe through envoriment variables to keep the interface easy.
Also what about `j` and `k` for up and down?
Sry for issueing again (:

**Comment by djt3** [comment]
No problem, any suggestions are appreciated. I have no idea how I overlooked those two, I'll be adding them today as well as j and k for up and down.

**Comment by djt3** [comment]
added in latest commit

**Comment by sdsddsd1** [comment]
I switched up and down in my suggestion.
Going after vim,
`j` is for `down`
`k` is for `up`

**Comment by sdsddsd1** [comment]
ping @djt3
