### ISSUE TITLE
Segfaulting since `fixed scrolling issue`

### ISSUE THREAD

**Issue by sdsddsd1** [djt3/tuitube#6]
Hey,
commit [05164c7](https://github.com/djt3/tuitube/commit/05164c76320d3bf1bc9a2904e56bf1440c498490) leads to segfaults on my end. Tested with `st` and `alacritty`.

**Comment by djt3** [comment]
Thanks, i just noticed this on my arch machine, everything working fine on bsd. I suggest reverting to v2 for now, sorry for the inconvenience.

**Comment by djt3** [comment]
fixed in the latest commit
