### ISSUE TITLE
Feature request: view subscribed channels only

### ISSUE THREAD

**Issue by sdsddsd1** [djt3/tuitube#8]
Hey,
I want to ask for a feature to have `a list which holds the subscribed channels`. Maybe just sorted by last updated.
I cant interpret this out of your to´do if this is already a planned.

**Comment by djt3** [comment]
thanks for the suggestion. ill be sure to add this after i finish changing the drawing and tab system.

**Comment by djt3** [comment]
added in latest commit, press 'L' on the subscription tab
